// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvgegpzrchderhbjihch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2Z2VncHpyY2hkZXJoYmppaGNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MDAyMjIsImV4cCI6MjA2NzQ3NjIyMn0.vNFAbMfYD33eguxKVZp9fdxQpl8aXx3erY_adn8I7TQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});